language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_deploy:
  - yarn install
  - yarn run predeploy
deploy:
  - provider: npm
    skip_cleanup: true
    email: vincevella0@gmail.com
    api_key:
      secure: mDejQMmBV/GrXqdPXUoijUcC8XTnsKwMy0z4bFqMck3BXSa7TO+NB1Vefzv32ysUEbfXKBVjmhx4HG5Le1j5G37+DFQsE2XoRMttJiHzJy578n/WJboSQqeXr5xoXZT9rkDtPntsZZH1SjLH1r2ucZIWHbFEHC3XIJ3zqvZbOoVitAHasbZ3nCgA/g331MolkJ/1czKRH85o9R/FD1VUWGdqH/pdzzz2JNtdFPvU451GENLAcWwEMxgCbcH9g8W4R3gX1MZwSIJB+F4w0NPePTu8OpfMCwdgnI6i35HXxXelqaN6c/8coOs3I/xZsJW1GdxLuytoZXdP8zq5tB/f4Kgf77CO0IV02IzedjMDvwypYFN90QpgVMyeBt4a97aLyPtFP9yAUSWKXdLm5fD28yNSv3lnuBSIbv/3MHmOr0sgyIrgVnhAGHzq70in/mMD2ISxSzHPK0D9MVbP6WA/Ihsm85MgSw+PtTPFvc1DkzE/HZogeWoYEnv3gJTiSmZU1vsGC0wOBwoH4EG0jH4rY2Be+1Rp37bzCmvguCfyYOi6AaT7yl2XvP8MJMUn4jlUDNDYJ+WRN47RSb+zccfn6YAa943G7YZYo041G9LGs1hfY5op+G08Jb6MrAwBV+u+pLcfPn/ckP/zfgsD+AGmXPsiA5bMSg7dcfaFmSl0kQs=
    on:
      tags: true
      repo: vincentvella/use-cooldown
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: example/build
    on:
      branch: master
